name: real_estate_pred
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  # Data Processing and Analysis
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  
  # Data Visualization
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  
  # Machine Learning
  - xgboost>=1.5.0
  - lightgbm>=3.3.0
  - catboost>=1.0.0
  
  # Jupyter Notebooks
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  
  # Utilities
  - python-dotenv>=0.19.0
  - pyyaml>=5.4.0
  
  # Testing
  - pytest>=6.2.0
  
  # Type Hints
  - typing-extensions>=3.10.0

  # pip packages can be added here if needed
  - pip
  - pip:
    # Add any packages that are only available via pip here 